language: python
cache: pip
python:
  - 3.8
env:
  - LOGGING=info
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - pip install --upgrade pytest pytest-cov setuptools wheel codecov pipenv pipenv-setup
  - pipenv --install
install:
  - python setup.py bdist_wheel
  - pip install dist/qiskit-aws-braket-provider*.whl
script:
  - python -m pytest tests --cov=qiskit-aws-braket-provider --cov-report term-missing --cov-report=html:coverage_html_report
after_success:
  - codecov